### ISSUE TITLE
How to do the text captcha with just the params

### ISSUE THREAD

**Issue by nagaharish** [matthutchinson/acts_as_textcaptcha#18]
Hi,
We have a requirement such that when ever a user wanted to reset password he will just submit the email id and we will send the email instructions to the user.

We wanted to implement the captcha here. Basically we don't even save any data but we wanted to validate the captcha with the parameters received.
Is there a way to do it? If so can you please explain.

**Comment by matthutchinson** [comment]
Yes, its possible to use the gem to validate a captcha on a non-active record object.  The README points to the Contact example in the test suite;

# the `Contact` class is defined and configured here;
https://github.com/matthutchinson/acts_as_textcaptcha/blob/master/test/test_models.rb#L44
(this class hasn't been configured to use the captcha API (it uses direct questions in the config), but you could change that)

# And this test shows how that model might be used (calling valid?) will let you check if the captcha is correct.

https://github.com/matthutchinson/acts_as_textcaptcha/blob/master/test/textcaptcha_test.rb#L51

For your situation, it would probably be best to pass the params to a dedicated Captcha class (similar to the Contact class in this example).  Since you probably don't want to put this on User directly, given you are only resetting a password.
